// AUTO-GENERATED – do not edit.
// Run: dart run ffigen --config ffigen.yaml
//
// ignore_for_file: type=lint
// ignore_for_file: return_of_invalid_type
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unused_element
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Bindings for the bclibc ballistics engine C API.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BcLibCFFIBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BcLibCFFIBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BcLibCFFIBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief Returns the library version string.
  ffi.Pointer<ffi.Char> BCLIBCFFI_get_version() {
    return _BCLIBCFFI_get_version();
  }

  late final _BCLIBCFFI_get_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'BCLIBCFFI_get_version',
      );
  late final _BCLIBCFFI_get_version =
      _BCLIBCFFI_get_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Find the apex (highest point) of the trajectory.
  /// @return BCLIBCFFI_OK on success, error code otherwise (fills *err).
  int BCLIBCFFI_find_apex(
    ffi.Pointer<BCLIBCFFI_ShotProps> props,
    ffi.Pointer<BCLIBCFFI_TrajectoryData> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_apex(props, out, err);
  }

  late final _BCLIBCFFI_find_apexPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_ShotProps>,
            ffi.Pointer<BCLIBCFFI_TrajectoryData>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_apex');
  late final _BCLIBCFFI_find_apex =
      _BCLIBCFFI_find_apexPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_ShotProps>,
          ffi.Pointer<BCLIBCFFI_TrajectoryData>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Find the maximum range and corresponding angle.
  /// @param low_angle_deg   Lower search bound (degrees).
  /// @param high_angle_deg  Upper search bound (degrees).
  int BCLIBCFFI_find_max_range(
    ffi.Pointer<BCLIBCFFI_ShotProps> props,
    double low_angle_deg,
    double high_angle_deg,
    ffi.Pointer<BCLIBCFFI_MaxRangeResult> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_max_range(
      props,
      low_angle_deg,
      high_angle_deg,
      out,
      err,
    );
  }

  late final _BCLIBCFFI_find_max_rangePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_ShotProps>,
            ffi.Double,
            ffi.Double,
            ffi.Pointer<BCLIBCFFI_MaxRangeResult>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_max_range');
  late final _BCLIBCFFI_find_max_range =
      _BCLIBCFFI_find_max_rangePtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_ShotProps>,
          double,
          double,
          ffi.Pointer<BCLIBCFFI_MaxRangeResult>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Find the barrel elevation angle to zero at the given distance.
  /// @param distance_ft     Slant distance to target (ft).
  /// @param out_angle_rad   Output: barrel elevation (radians).
  int BCLIBCFFI_find_zero_angle(
    ffi.Pointer<BCLIBCFFI_ShotProps> props,
    double distance_ft,
    ffi.Pointer<ffi.Double> out_angle_rad,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_zero_angle(props, distance_ft, out_angle_rad, err);
  }

  late final _BCLIBCFFI_find_zero_anglePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_ShotProps>,
            ffi.Double,
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_zero_angle');
  late final _BCLIBCFFI_find_zero_angle =
      _BCLIBCFFI_find_zero_anglePtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_ShotProps>,
          double,
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Integrate trajectory and return filtered records.
  ///
  /// On success *out_records points to a heap-allocated BCLIBCFFI_TrajectoryData array
  /// of length *out_count.  Call BCLIBCFFI_free_trajectory() to release it.
  int BCLIBCFFI_integrate(
    ffi.Pointer<BCLIBCFFI_ShotProps> props,
    ffi.Pointer<BCLIBCFFI_TrajectoryRequest> request,
    ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>> out_records,
    ffi.Pointer<ffi.Int32> out_count,
    ffi.Pointer<ffi.Int32> out_reason,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_integrate(
      props,
      request,
      out_records,
      out_count,
      out_reason,
      err,
    );
  }

  late final _BCLIBCFFI_integratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_ShotProps>,
            ffi.Pointer<BCLIBCFFI_TrajectoryRequest>,
            ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_integrate');
  late final _BCLIBCFFI_integrate =
      _BCLIBCFFI_integratePtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_ShotProps>,
          ffi.Pointer<BCLIBCFFI_TrajectoryRequest>,
          ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Free a trajectory array allocated by BCLIBCFFI_integrate().
  void BCLIBCFFI_free_trajectory(
    ffi.Pointer<BCLIBCFFI_TrajectoryData> records,
  ) {
    return _BCLIBCFFI_free_trajectory(records);
  }

  late final _BCLIBCFFI_free_trajectoryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<BCLIBCFFI_TrajectoryData>)
        >
      >('BCLIBCFFI_free_trajectory');
  late final _BCLIBCFFI_free_trajectory =
      _BCLIBCFFI_free_trajectoryPtr.asFunction<
        void Function(ffi.Pointer<BCLIBCFFI_TrajectoryData>)
      >();

  /// Integrate and interpolate the single point where a key field reaches
  /// the target value.
  /// @param key          BCLIBCFFI_BaseTrajInterpKey
  /// @param target_value Value the key field must reach.
  int BCLIBCFFI_integrate_at(
    ffi.Pointer<BCLIBCFFI_ShotProps> props,
    int key,
    double target_value,
    ffi.Pointer<BCLIBCFFI_Interception> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_integrate_at(props, key, target_value, out, err);
  }

  late final _BCLIBCFFI_integrate_atPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_ShotProps>,
            ffi.Int32,
            ffi.Double,
            ffi.Pointer<BCLIBCFFI_Interception>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_integrate_at');
  late final _BCLIBCFFI_integrate_at =
      _BCLIBCFFI_integrate_atPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_ShotProps>,
          int,
          double,
          ffi.Pointer<BCLIBCFFI_Interception>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Find the apex of the trajectory.
  /// All physics/unit conversion is performed inside C++ via BCLIBCFFI_Shot::to_shot_props().
  int BCLIBCFFI_find_apex_shot(
    ffi.Pointer<BCLIBCFFI_Shot> shot,
    ffi.Pointer<BCLIBCFFI_TrajectoryData> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_apex_shot(shot, out, err);
  }

  late final _BCLIBCFFI_find_apex_shotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_Shot>,
            ffi.Pointer<BCLIBCFFI_TrajectoryData>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_apex_shot');
  late final _BCLIBCFFI_find_apex_shot =
      _BCLIBCFFI_find_apex_shotPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_Shot>,
          ffi.Pointer<BCLIBCFFI_TrajectoryData>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  int BCLIBCFFI_find_max_range_shot(
    ffi.Pointer<BCLIBCFFI_Shot> shot,
    double low_angle_deg,
    double high_angle_deg,
    ffi.Pointer<BCLIBCFFI_MaxRangeResult> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_max_range_shot(
      shot,
      low_angle_deg,
      high_angle_deg,
      out,
      err,
    );
  }

  late final _BCLIBCFFI_find_max_range_shotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_Shot>,
            ffi.Double,
            ffi.Double,
            ffi.Pointer<BCLIBCFFI_MaxRangeResult>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_max_range_shot');
  late final _BCLIBCFFI_find_max_range_shot =
      _BCLIBCFFI_find_max_range_shotPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_Shot>,
          double,
          double,
          ffi.Pointer<BCLIBCFFI_MaxRangeResult>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  int BCLIBCFFI_find_zero_angle_shot(
    ffi.Pointer<BCLIBCFFI_Shot> shot,
    double distance_ft,
    ffi.Pointer<ffi.Double> out_angle_rad,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_find_zero_angle_shot(
      shot,
      distance_ft,
      out_angle_rad,
      err,
    );
  }

  late final _BCLIBCFFI_find_zero_angle_shotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_Shot>,
            ffi.Double,
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_find_zero_angle_shot');
  late final _BCLIBCFFI_find_zero_angle_shot =
      _BCLIBCFFI_find_zero_angle_shotPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_Shot>,
          double,
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  int BCLIBCFFI_integrate_shot(
    ffi.Pointer<BCLIBCFFI_Shot> shot,
    ffi.Pointer<BCLIBCFFI_TrajectoryRequest> request,
    ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>> out_records,
    ffi.Pointer<ffi.Int32> out_count,
    ffi.Pointer<ffi.Int32> out_reason,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_integrate_shot(
      shot,
      request,
      out_records,
      out_count,
      out_reason,
      err,
    );
  }

  late final _BCLIBCFFI_integrate_shotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_Shot>,
            ffi.Pointer<BCLIBCFFI_TrajectoryRequest>,
            ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_integrate_shot');
  late final _BCLIBCFFI_integrate_shot =
      _BCLIBCFFI_integrate_shotPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_Shot>,
          ffi.Pointer<BCLIBCFFI_TrajectoryRequest>,
          ffi.Pointer<ffi.Pointer<BCLIBCFFI_TrajectoryData>>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  int BCLIBCFFI_integrate_at_shot(
    ffi.Pointer<BCLIBCFFI_Shot> shot,
    int key,
    double target_value,
    ffi.Pointer<BCLIBCFFI_Interception> out,
    ffi.Pointer<BCLIBCFFI_Error> err,
  ) {
    return _BCLIBCFFI_integrate_at_shot(shot, key, target_value, out, err);
  }

  late final _BCLIBCFFI_integrate_at_shotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<BCLIBCFFI_Shot>,
            ffi.Int32,
            ffi.Double,
            ffi.Pointer<BCLIBCFFI_Interception>,
            ffi.Pointer<BCLIBCFFI_Error>,
          )
        >
      >('BCLIBCFFI_integrate_at_shot');
  late final _BCLIBCFFI_integrate_at_shot =
      _BCLIBCFFI_integrate_at_shotPtr.asFunction<
        int Function(
          ffi.Pointer<BCLIBCFFI_Shot>,
          int,
          double,
          ffi.Pointer<BCLIBCFFI_Interception>,
          ffi.Pointer<BCLIBCFFI_Error>,
        )
      >();

  /// Angular correction (radians) to hit target at distance with given offset.
  double BCLIBCFFI_get_correction(double distance_ft, double offset_ft) {
    return _BCLIBCFFI_get_correction(distance_ft, offset_ft);
  }

  late final _BCLIBCFFI_get_correctionPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
        'BCLIBCFFI_get_correction',
      );
  late final _BCLIBCFFI_get_correction =
      _BCLIBCFFI_get_correctionPtr.asFunction<
        double Function(double, double)
      >();

  /// Kinetic energy (ft-lb) from bullet weight (grains) and velocity (fps).
  double BCLIBCFFI_calculate_energy(
    double bullet_weight_grain,
    double velocity_fps,
  ) {
    return _BCLIBCFFI_calculate_energy(bullet_weight_grain, velocity_fps);
  }

  late final _BCLIBCFFI_calculate_energyPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
        'BCLIBCFFI_calculate_energy',
      );
  late final _BCLIBCFFI_calculate_energy =
      _BCLIBCFFI_calculate_energyPtr.asFunction<
        double Function(double, double)
      >();

  /// Optimal Game Weight from bullet weight (grains) and velocity (fps).
  double BCLIBCFFI_calculate_ogw(
    double bullet_weight_grain,
    double velocity_fps,
  ) {
    return _BCLIBCFFI_calculate_ogw(bullet_weight_grain, velocity_fps);
  }

  late final _BCLIBCFFI_calculate_ogwPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Double, ffi.Double)>>(
        'BCLIBCFFI_calculate_ogw',
      );
  late final _BCLIBCFFI_calculate_ogw =
      _BCLIBCFFI_calculate_ogwPtr.asFunction<double Function(double, double)>();
}

enum BCLIBCFFI_Status {
  BCLIBCFFI_OK(0),
  BCLIBCFFI_ERR_SOLVER_RUNTIME(1),
  BCLIBCFFI_ERR_OUT_OF_RANGE(2),
  BCLIBCFFI_ERR_ZERO_FINDING(3),
  BCLIBCFFI_ERR_INTERCEPTION(4),
  BCLIBCFFI_ERR_GENERIC(5);

  final int value;
  const BCLIBCFFI_Status(this.value);

  static BCLIBCFFI_Status fromValue(int value) => switch (value) {
    0 => BCLIBCFFI_OK,
    1 => BCLIBCFFI_ERR_SOLVER_RUNTIME,
    2 => BCLIBCFFI_ERR_OUT_OF_RANGE,
    3 => BCLIBCFFI_ERR_ZERO_FINDING,
    4 => BCLIBCFFI_ERR_INTERCEPTION,
    5 => BCLIBCFFI_ERR_GENERIC,
    _ => throw ArgumentError('Unknown value for BCLIBCFFI_Status: $value'),
  };
}

/// Error output struct – filled by every function on failure.
final class BCLIBCFFI_Error extends ffi.Struct {
  /// < BCLIBCFFI_Status
  @ffi.Int32()
  external int code;

  /// < Null-terminated error message
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> message;

  /// < OutOfRange: requested_distance_ft / ZeroFinding: zero_finding_error
  @ffi.Double()
  external double f64_0;

  /// < OutOfRange: max_range_ft          / ZeroFinding: last_barrel_elevation_rad
  @ffi.Double()
  external double f64_1;

  /// < OutOfRange: look_angle_rad
  @ffi.Double()
  external double f64_2;

  /// < ZeroFinding: iterations_count
  @ffi.Int32()
  external int i32_0;
}

enum BCLIBCFFI_TrajFlag {
  BCLIBCFFI_TRAJ_FLAG_NONE(0),
  BCLIBCFFI_TRAJ_FLAG_ZERO_UP(1),
  BCLIBCFFI_TRAJ_FLAG_ZERO_DOWN(2),
  BCLIBCFFI_TRAJ_FLAG_ZERO(3),
  BCLIBCFFI_TRAJ_FLAG_MACH(4),
  BCLIBCFFI_TRAJ_FLAG_RANGE(8),
  BCLIBCFFI_TRAJ_FLAG_APEX(16),
  BCLIBCFFI_TRAJ_FLAG_ALL(31),
  BCLIBCFFI_TRAJ_FLAG_MRT(32);

  final int value;
  const BCLIBCFFI_TrajFlag(this.value);

  static BCLIBCFFI_TrajFlag fromValue(int value) => switch (value) {
    0 => BCLIBCFFI_TRAJ_FLAG_NONE,
    1 => BCLIBCFFI_TRAJ_FLAG_ZERO_UP,
    2 => BCLIBCFFI_TRAJ_FLAG_ZERO_DOWN,
    3 => BCLIBCFFI_TRAJ_FLAG_ZERO,
    4 => BCLIBCFFI_TRAJ_FLAG_MACH,
    8 => BCLIBCFFI_TRAJ_FLAG_RANGE,
    16 => BCLIBCFFI_TRAJ_FLAG_APEX,
    31 => BCLIBCFFI_TRAJ_FLAG_ALL,
    32 => BCLIBCFFI_TRAJ_FLAG_MRT,
    _ => throw ArgumentError('Unknown value for BCLIBCFFI_TrajFlag: $value'),
  };
}

enum BCLIBCFFI_TerminationReason {
  BCLIBCFFI_TERM_NO_TERMINATE(0),
  BCLIBCFFI_TERM_TARGET_RANGE_REACHED(1),
  BCLIBCFFI_TERM_MINIMUM_VELOCITY_REACHED(2),
  BCLIBCFFI_TERM_MAXIMUM_DROP_REACHED(3),
  BCLIBCFFI_TERM_MINIMUM_ALTITUDE_REACHED(4),
  BCLIBCFFI_TERM_HANDLER_REQUESTED_STOP(5);

  final int value;
  const BCLIBCFFI_TerminationReason(this.value);

  static BCLIBCFFI_TerminationReason fromValue(int value) => switch (value) {
    0 => BCLIBCFFI_TERM_NO_TERMINATE,
    1 => BCLIBCFFI_TERM_TARGET_RANGE_REACHED,
    2 => BCLIBCFFI_TERM_MINIMUM_VELOCITY_REACHED,
    3 => BCLIBCFFI_TERM_MAXIMUM_DROP_REACHED,
    4 => BCLIBCFFI_TERM_MINIMUM_ALTITUDE_REACHED,
    5 => BCLIBCFFI_TERM_HANDLER_REQUESTED_STOP,
    _ => throw ArgumentError(
      'Unknown value for BCLIBCFFI_TerminationReason: $value',
    ),
  };
}

/// Interpolation key for BCLIBC_BaseTrajData fields.
enum BCLIBCFFI_BaseTrajInterpKey {
  BCLIBCFFI_INTERP_KEY_TIME(0),
  BCLIBCFFI_INTERP_KEY_MACH(1),
  BCLIBCFFI_INTERP_KEY_POS_X(2),
  BCLIBCFFI_INTERP_KEY_POS_Y(3),
  BCLIBCFFI_INTERP_KEY_POS_Z(4),
  BCLIBCFFI_INTERP_KEY_VEL_X(5),
  BCLIBCFFI_INTERP_KEY_VEL_Y(6),
  BCLIBCFFI_INTERP_KEY_VEL_Z(7);

  final int value;
  const BCLIBCFFI_BaseTrajInterpKey(this.value);

  static BCLIBCFFI_BaseTrajInterpKey fromValue(int value) => switch (value) {
    0 => BCLIBCFFI_INTERP_KEY_TIME,
    1 => BCLIBCFFI_INTERP_KEY_MACH,
    2 => BCLIBCFFI_INTERP_KEY_POS_X,
    3 => BCLIBCFFI_INTERP_KEY_POS_Y,
    4 => BCLIBCFFI_INTERP_KEY_POS_Z,
    5 => BCLIBCFFI_INTERP_KEY_VEL_X,
    6 => BCLIBCFFI_INTERP_KEY_VEL_Y,
    7 => BCLIBCFFI_INTERP_KEY_VEL_Z,
    _ => throw ArgumentError(
      'Unknown value for BCLIBCFFI_BaseTrajInterpKey: $value',
    ),
  };
}

enum BCLIBCFFI_IntegrationMethod {
  BCLIBCFFI_INTEGRATION_RK4(0),
  BCLIBCFFI_INTEGRATION_EULER(1);

  final int value;
  const BCLIBCFFI_IntegrationMethod(this.value);

  static BCLIBCFFI_IntegrationMethod fromValue(int value) => switch (value) {
    0 => BCLIBCFFI_INTEGRATION_RK4,
    1 => BCLIBCFFI_INTEGRATION_EULER,
    _ => throw ArgumentError(
      'Unknown value for BCLIBCFFI_IntegrationMethod: $value',
    ),
  };
}

final class BCLIBCFFI_Config extends ffi.Struct {
  @ffi.Double()
  external double cStepMultiplier;

  @ffi.Double()
  external double cZeroFindingAccuracy;

  @ffi.Double()
  external double cMinimumVelocity;

  @ffi.Double()
  external double cMaximumDrop;

  @ffi.Int32()
  external int cMaxIterations;

  @ffi.Double()
  external double cGravityConstant;

  @ffi.Double()
  external double cMinimumAltitude;
}

final class BCLIBCFFI_Atmosphere extends ffi.Struct {
  /// < Temperature at base altitude (°F)
  @ffi.Double()
  external double t0;

  /// < Base altitude (ft)
  @ffi.Double()
  external double a0;

  /// < Pressure at base altitude (hPa)
  @ffi.Double()
  external double p0;

  /// < Speed of sound (fps)
  @ffi.Double()
  external double mach;

  /// < Air density / standard density
  @ffi.Double()
  external double density_ratio;

  /// < Lowest allowed temperature (°C)
  @ffi.Double()
  external double cLowestTempC;
}

final class BCLIBCFFI_Coriolis extends ffi.Struct {
  @ffi.Double()
  external double sin_lat;

  @ffi.Double()
  external double cos_lat;

  @ffi.Double()
  external double sin_az;

  @ffi.Double()
  external double cos_az;

  @ffi.Double()
  external double range_east;

  @ffi.Double()
  external double range_north;

  @ffi.Double()
  external double cross_east;

  @ffi.Double()
  external double cross_north;

  /// < Non-zero = flat-fire approximation
  @ffi.Int32()
  external int flat_fire_only;

  @ffi.Double()
  external double muzzle_velocity_fps;
}

final class BCLIBCFFI_Wind extends ffi.Struct {
  @ffi.Double()
  external double velocity_fps;

  @ffi.Double()
  external double direction_from_rad;

  @ffi.Double()
  external double until_distance_ft;

  /// < Sentinel for last segment (use BCLIBC_cMaxWindDistanceFeet)
  @ffi.Double()
  external double max_distance_ft;
}

final class BCLIBCFFI_DragPoint extends ffi.Struct {
  @ffi.Double()
  external double Mach;

  @ffi.Double()
  external double CD;
}

/// Flat shot properties passed to every engine function.
final class BCLIBCFFI_ShotProps extends ffi.Struct {
  @ffi.Double()
  external double bc;

  @ffi.Double()
  external double look_angle_rad;

  @ffi.Double()
  external double twist_inch;

  @ffi.Double()
  external double length_inch;

  @ffi.Double()
  external double diameter_inch;

  @ffi.Double()
  external double weight_grain;

  @ffi.Double()
  external double barrel_elevation_rad;

  @ffi.Double()
  external double barrel_azimuth_rad;

  @ffi.Double()
  external double sight_height_ft;

  @ffi.Double()
  external double cant_angle_rad;

  @ffi.Double()
  external double alt0_ft;

  @ffi.Double()
  external double muzzle_velocity_fps;

  external BCLIBCFFI_Atmosphere atmo;

  external BCLIBCFFI_Coriolis coriolis;

  external BCLIBCFFI_Config config;

  @ffi.UnsignedInt()
  external int methodAsInt;

  BCLIBCFFI_IntegrationMethod get method =>
      BCLIBCFFI_IntegrationMethod.fromValue(methodAsInt);

  /// Drag table – pointer must remain valid for the duration of the call.
  external ffi.Pointer<BCLIBCFFI_DragPoint> drag_table;

  @ffi.Int32()
  external int drag_table_count;

  /// Wind list – pointer must remain valid for the duration of the call.
  external ffi.Pointer<BCLIBCFFI_Wind> winds;

  @ffi.Int32()
  external int wind_count;
}

/// User-facing shot descriptor in natural units.
///
/// Preferred input for BCLIBCFFI_*_shot() functions.  All physics conversions
/// (CIPM-2007 atmosphere density, Coriolis trig, PCHIP drag curve, cant sin/cos)
/// are performed inside C++ by BCLIBC_Shot::to_shot_props().
///
/// latitude_deg / azimuth_deg: pass NaN to disable Coriolis / flat-fire-only.
/// pressure_hpa == 0          : vacuum (zero drag).
///
/// All pointers must remain valid for the duration of the call.
/// Drag table is passed as two parallel arrays (mach_data / cd_data) matching
/// the BCLIBC_Shot layout — no interleaved struct needed.
final class BCLIBCFFI_Shot extends ffi.Struct {
  @ffi.Double()
  external double bc;

  @ffi.Double()
  external double weight_grain;

  @ffi.Double()
  external double diameter_inch;

  @ffi.Double()
  external double length_inch;

  @ffi.Double()
  external double muzzle_velocity_fps;

  @ffi.Double()
  external double sight_height_ft;

  @ffi.Double()
  external double twist_inch;

  @ffi.Double()
  external double temp_c;

  /// < 0 = vacuum
  @ffi.Double()
  external double pressure_hpa;

  @ffi.Double()
  external double altitude_ft;

  /// < 0.0 – 1.0
  @ffi.Double()
  external double humidity;

  /// Parallel Mach / CD arrays – must remain valid for the duration of the call.
  external ffi.Pointer<ffi.Double> mach_data;

  external ffi.Pointer<ffi.Double> cd_data;

  @ffi.Int32()
  external int drag_table_size;

  /// Wind list – must remain valid for the duration of the call.
  external ffi.Pointer<BCLIBCFFI_Wind> winds;

  @ffi.Int32()
  external int wind_count;

  @ffi.Double()
  external double look_angle_rad;

  @ffi.Double()
  external double barrel_elevation_rad;

  @ffi.Double()
  external double barrel_azimuth_rad;

  @ffi.Double()
  external double cant_angle_rad;

  @ffi.Double()
  external double latitude_deg;

  @ffi.Double()
  external double azimuth_deg;

  external BCLIBCFFI_Config config;

  @ffi.UnsignedInt()
  external int methodAsInt;

  BCLIBCFFI_IntegrationMethod get method =>
      BCLIBCFFI_IntegrationMethod.fromValue(methodAsInt);
}

final class BCLIBCFFI_TrajectoryRequest extends ffi.Struct {
  @ffi.Double()
  external double range_limit_ft;

  @ffi.Double()
  external double range_step_ft;

  @ffi.Double()
  external double time_step;

  /// < BCLIBCFFI_TrajFlag bitmask
  @ffi.Int32()
  external int filter_flags;
}

final class BCLIBCFFI_BaseTrajData extends ffi.Struct {
  @ffi.Double()
  external double time;

  /// < Position x (downrange, ft)
  @ffi.Double()
  external double px;

  /// < Position y (height, ft)
  @ffi.Double()
  external double py;

  /// < Position z (windage, ft)
  @ffi.Double()
  external double pz;

  /// < Velocity x (fps)
  @ffi.Double()
  external double vx;

  /// < Velocity y (fps)
  @ffi.Double()
  external double vy;

  /// < Velocity z (fps)
  @ffi.Double()
  external double vz;

  @ffi.Double()
  external double mach;
}

final class BCLIBCFFI_TrajectoryData extends ffi.Struct {
  @ffi.Double()
  external double time;

  @ffi.Double()
  external double distance_ft;

  @ffi.Double()
  external double velocity_fps;

  @ffi.Double()
  external double mach;

  @ffi.Double()
  external double height_ft;

  @ffi.Double()
  external double slant_height_ft;

  @ffi.Double()
  external double drop_angle_rad;

  @ffi.Double()
  external double windage_ft;

  @ffi.Double()
  external double windage_angle_rad;

  @ffi.Double()
  external double slant_distance_ft;

  @ffi.Double()
  external double angle_rad;

  @ffi.Double()
  external double density_ratio;

  @ffi.Double()
  external double drag;

  @ffi.Double()
  external double energy_ft_lb;

  @ffi.Double()
  external double ogw_lb;

  /// < BCLIBCFFI_TrajFlag
  @ffi.Int32()
  external int flag;
}

final class BCLIBCFFI_MaxRangeResult extends ffi.Struct {
  @ffi.Double()
  external double max_range_ft;

  @ffi.Double()
  external double angle_at_max_rad;
}

final class BCLIBCFFI_Interception extends ffi.Struct {
  external BCLIBCFFI_BaseTrajData raw_data;

  external BCLIBCFFI_TrajectoryData full_data;
}
