import 'package:json_schema/json_schema.dart';

import '../generated/ebcp_schema.g.dart';
import '../proto/ebcp.pb.dart' as proto;
import 'profiles_json.dart';
import 'settings_json.dart';

class EbcpFieldError {
  final String field;
  final String message;
  const EbcpFieldError(this.field, this.message);

  @override
  String toString() => '$field: $message';
}

class EbcpValidationException implements Exception {
  final List<EbcpFieldError> errors;
  const EbcpValidationException(this.errors);

  @override
  String toString() => 'EbcpData validation failed:\n${errors.join('\n')}';
}

abstract final class EbcpValidator {
  // Built once from the embedded schema constant (kEbcpSchemaJson,
  // generated by bin/embed_schema.dart, which inlines profiles.schema.json/
  // settings.schema.json's $defs so this is self-contained) and reused for
  // every validate() call.
  static JsonSchema? _schemaCache;
  static JsonSchema get _schema =>
      _schemaCache ??= JsonSchema.create(kEbcpSchemaJson);

  static void validate(proto.EbcpData data) {
    final json = _ebcpDataToJson(data);
    final results = _schema.validate(json);
    if (results.errors.isEmpty) return;

    final errors = [
      for (final e in results.errors)
        EbcpFieldError(_fieldPath(e.instancePath), e.message),
    ];
    throw EbcpValidationException(errors);
  }

  // json_schema reports errors as JSON Pointers (e.g. "/profiles_data/0/profiles/0");
  // strip the leading slash so field paths read like a normal accessor path.
  static String _fieldPath(String instancePath) {
    var path = instancePath;
    if (path.startsWith('/')) path = path.substring(1);
    return path.isEmpty ? 'ebcp' : path;
  }

  static Map<String, dynamic> _ebcpDataToJson(proto.EbcpData data) => {
    'schema_version': data.schemaVersion,
    'profiles_data': data.profilesData.map(profilesDataToJson).toList(),
    if (data.hasSettingsData()) 'settings_data': settingsDataToJson(data.settingsData),
  };
}
