import 'package:json_schema/json_schema.dart';

import 'generated/ebc_db_schema.g.dart';
import 'proto/ebc_db.pb.dart' as proto;

class DbFieldError {
  final String field;
  final String message;
  const DbFieldError(this.field, this.message);

  @override
  String toString() => '$field: $message';
}

class DbValidationException implements Exception {
  final List<DbFieldError> errors;
  const DbValidationException(this.errors);

  @override
  String toString() => 'Db validation failed:\n${errors.join('\n')}';
}

abstract final class DbValidator {
  // Built once from the embedded schema constant (kEbcDbSchemaJson,
  // generated by bin/embed_schema.dart) and reused for every validate()
  // call — JsonSchema.create() parses the whole schema, so this avoids
  // repeating that work per validation.
  static JsonSchema? _schemaCache;
  static JsonSchema get _schema =>
      _schemaCache ??= JsonSchema.create(kEbcDbSchemaJson);

  static void validate(proto.Db db) {
    final data = _dbToJson(db);
    final results = _schema.validate(data);
    if (results.errors.isEmpty) return;

    final errors = [
      for (final e in results.errors)
        DbFieldError(_fieldPath(e.instancePath), e.message),
    ];
    throw DbValidationException(errors);
  }

  // json_schema reports errors as JSON Pointers (e.g. "/profiles/0/weapon");
  // strip the leading slash so field paths read like a normal accessor path.
  static String _fieldPath(String instancePath) {
    var path = instancePath;
    if (path.startsWith('/')) path = path.substring(1);
    return path.isEmpty ? 'db' : path;
  }

  // Converts the protobuf Db into the plain snake_case JSON shape
  // schema/ebc_db.schema.json is written against. Dart protobuf's own
  // writeToJsonMap() uses camelCase (proto3 JSON mapping), which wouldn't
  // match the schema's property names, so this is built by hand instead
  // (same reason a7p's A7pValidator does its own conversion).
  static Map<String, dynamic> _dbToJson(proto.Db db) => {
    'schema_version': db.schemaVersion,
    'general_settings': _generalSettingsToJson(db.generalSettings),
    'unit_settings': _unitSettingsToJson(db.unitSettings),
    'tables_settings': _tablesSettingsToJson(db.tablesSettings),
    'reticle_settings': _reticleSettingsToJson(db.reticleSettings),
    'convertors_state': _convertorsStateToJson(db.convertorsState),
    'shooting_conditions': _shootingConditionsToJson(db.shootingConditions),
    'profiles': db.profiles.map(_profileToJson).toList(),
  };

  static Map<String, dynamic> _weaponToJson(proto.Weapon w) => {
    'name': w.name,
    'caliber_inch': w.hasCaliberInch() ? w.caliberInch : null,
    'caliber_name': w.caliberName,
    'twist_inch': w.twistInch,
    'barrel_length_inch': w.hasBarrelLengthInch() ? w.barrelLengthInch : null,
    'zero_elevation_rad': w.zeroElevationRad,
    'vendor': w.vendor,
    'notes': w.notes,
    'image': w.image,
  };

  static Map<String, dynamic> _sightToJson(proto.Sight s) => {
    'ui_key': s.uiKey,
    'name': s.name,
    'focal_plane_value': s.focalPlaneValue,
    'sight_height_inch': s.sightHeightInch,
    'sight_horizontal_offset_inch': s.sightHorizontalOffsetInch,
    'vertical_click': s.verticalClick,
    'horizontal_click': s.horizontalClick,
    'vertical_click_unit': s.verticalClickUnit,
    'horizontal_click_unit': s.horizontalClickUnit,
    'min_magnification': s.minMagnification,
    'max_magnification': s.maxMagnification,
    'reticle_image': s.reticleImage,
    'calibrated_magnification': s.hasCalibratedMagnification()
        ? s.calibratedMagnification
        : null,
    'vendor': s.vendor,
    'notes': s.notes,
    'image': s.image,
  };

  static Map<String, dynamic> _ammoToJson(proto.Ammo a) => {
    'ui_key': a.uiKey,
    'name': a.name,
    'caliber_inch': a.hasCaliberInch() ? a.caliberInch : null,
    'weight_grain': a.hasWeightGrain() ? a.weightGrain : null,
    'length_inch': a.hasLengthInch() ? a.lengthInch : null,
    'drag_type_value': a.dragTypeValue,
    'bc_g1': a.hasBcG1() ? a.bcG1 : null,
    'bc_g7': a.hasBcG7() ? a.bcG7 : null,
    'use_multi_bc_g1': a.useMultiBcG1,
    'use_multi_bc_g7': a.useMultiBcG7,
    'muzzle_velocity_mps': a.hasMuzzleVelocityMps() ? a.muzzleVelocityMps : null,
    'muzzle_velocity_temperature_c': a.muzzleVelocityTemperatureC,
    'use_powder_sensitivity': a.usePowderSensitivity,
    'powder_sensitivity_frac': a.powderSensitivityFrac,
    'powder_sensitivity_tc': a.powderSensitivityTc,
    'powder_sensitivity_v_mps': a.powderSensitivityVMps,
    'multi_bc_table_g1_v_mps': a.multiBcTableG1VMps,
    'multi_bc_table_g1_bc': a.multiBcTableG1Bc,
    'multi_bc_table_g7_v_mps': a.multiBcTableG7VMps,
    'multi_bc_table_g7_bc': a.multiBcTableG7Bc,
    'custom_drag_table_mach': a.customDragTableMach,
    'custom_drag_table_cd': a.customDragTableCd,
    'zero': _zeroToJson(a.zero),
    'projectile_name': a.projectileName,
    'vendor': a.vendor,
    'image': a.image,
  };

  static Map<String, dynamic> _zeroToJson(proto.Zero z) => {
    'distance_meter': z.distanceMeter,
    'look_angle_rad': z.lookAngleRad,
    'altitude_meter': z.altitudeMeter,
    'temperature_c': z.temperatureC,
    'pressure_h_pa': z.pressureHPa,
    'humidity_frac': z.humidityFrac,
    'use_diff_powder_temperature': z.useDiffPowderTemperature,
    'use_coriolis': z.useCoriolis,
    'powder_temperature_c': z.powderTemperatureC,
    'latitude_deg': z.latitudeDeg,
    'azimuth_deg': z.azimuthDeg,
    'offset_x': z.offsetX,
    'offset_y': z.offsetY,
    'offset_x_unit': z.offsetXUnit,
    'offset_y_unit': z.offsetYUnit,
  };

  static Map<String, dynamic> _profileToJson(proto.Profile p) => {
    'ui_key': p.uiKey,
    'name': p.name,
    'weapon': _weaponToJson(p.weapon),
    'ammo': p.ammo.map(_ammoToJson).toList(),
    'sights': p.sights.map(_sightToJson).toList(),
  };

  static Map<String, dynamic> _generalSettingsToJson(
    proto.GeneralSettings g,
  ) => {
    'language_code': g.languageCode,
    'theme_mode': g.themeMode,
    'adjustment_display_format_value': g.adjustmentDisplayFormatValue,
    'home_show_mil': g.homeShowMil,
    'home_show_mrad': g.homeShowMrad,
    'home_show_moa': g.homeShowMoa,
    'home_show_cm_per100m': g.homeShowCmPer100m,
    'home_show_in_per100yd': g.homeShowInPer100yd,
    'home_show_in_clicks': g.homeShowInClicks,
    'home_chart_distance_step': g.homeChartDistanceStep,
    'home_table_distance_step': g.homeTableDistanceStep,
    'home_show_subsonic_transition': g.homeShowSubsonicTransition,
  };

  static Map<String, dynamic> _tablesSettingsToJson(proto.TablesSettings t) => {
    'distance_start_meter': t.distanceStartMeter,
    'distance_end_meter': t.distanceEndMeter,
    'distance_step_meter': t.distanceStepMeter,
    'show_zeros': t.showZeros,
    'show_subsonic_transition': t.showSubsonicTransition,
    'hidden_cols': t.hiddenCols,
    'show_mil': t.showMil,
    'show_mrad': t.showMrad,
    'show_moa': t.showMoa,
    'show_cm_per100m': t.showCmPer100m,
    'show_in_per100yd': t.showInPer100yd,
    'show_in_clicks': t.showInClicks,
  };

  static Map<String, dynamic> _unitSettingsToJson(proto.UnitSettings u) => {
    'angular': u.angular,
    'distance': u.distance,
    'velocity': u.velocity,
    'pressure': u.pressure,
    'temperature': u.temperature,
    'diameter': u.diameter,
    'length': u.length,
    'weight': u.weight,
    'adjustment': u.adjustment,
    'drop': u.drop,
    'energy': u.energy,
    'sight_height': u.sightHeight,
    'twist': u.twist,
    'barrel_length': u.barrelLength,
    'time': u.time,
    'torque': u.torque,
    'target_size': u.targetSize,
  };

  static Map<String, dynamic> _shootingConditionsToJson(
    proto.ShootingConditions s,
  ) => {
    'distance_meter': s.distanceMeter,
    'look_angle_rad': s.lookAngleRad,
    'altitude_meter': s.altitudeMeter,
    'temperature_c': s.temperatureC,
    'pressure_h_pa': s.pressureHPa,
    'humidity_frac': s.humidityFrac,
    'powder_temperature_c': s.powderTemperatureC,
    'use_powder_sensitivity': s.usePowderSensitivity,
    'use_diff_powder_temp': s.useDiffPowderTemp,
    'use_coriolis': s.useCoriolis,
    'latitude_deg': s.latitudeDeg,
    'azimuth_deg': s.azimuthDeg,
    'wind_direction_deg': s.windDirectionDeg,
    'wind_speed_mps': s.windSpeedMps,
  };

  static Map<String, dynamic> _unitValueToJson(proto.UnitValue u) => {
    'value': u.value,
    'last_unit': u.lastUnit,
  };

  static Map<String, dynamic> _anglesConvToJson(proto.AnglesConv a) => {
    'distance_value_meter': a.distanceValueMeter,
    'distance_last_unit': a.distanceLastUnit,
    'angular_value_mil': a.angularValueMil,
    'angular_last_unit': a.angularLastUnit,
    'output_last_unit': a.outputLastUnit,
  };

  static Map<String, dynamic> _velocityConvToJson(proto.VelocityConv v) => {
    'value_mps': v.valueMps,
    'last_unit': v.lastUnit,
    'mach_input_value': v.machInputValue,
    'mach_use_custom_atmo': v.machUseCustomAtmo,
    'atmo_temperature_c': v.atmoTemperatureC,
    'atmo_pressure_h_pa': v.atmoPressureHPa,
    'atmo_humidity_frac': v.atmoHumidityFrac,
    'atmo_altitude_meter': v.atmoAltitudeMeter,
  };

  static Map<String, dynamic> _distanceConvTargetSizeToJson(
    proto.DistanceConvTargetSize d,
  ) => {
    'size_inch': d.sizeInch,
    'size_unit': d.sizeUnit,
    'size_angular_mil': d.sizeAngularMil,
    'size_angular_unit': d.sizeAngularUnit,
  };

  static Map<String, dynamic> _convertorsStateToJson(
    proto.ConvertorsState c,
  ) => {
    'length': _unitValueToJson(c.length),
    'weight': _unitValueToJson(c.weight),
    'pressure': _unitValueToJson(c.pressure),
    'temperature': _unitValueToJson(c.temperature),
    'torque': _unitValueToJson(c.torque),
    'angles': _anglesConvToJson(c.angles),
    'velocity': _velocityConvToJson(c.velocity),
    'distance_conv_target_size': _distanceConvTargetSizeToJson(
      c.distanceConvTargetSize,
    ),
  };

  static Map<String, dynamic> _reticleSettingsToJson(
    proto.ReticleSettings r,
  ) => {
    'vertical_adjustment': r.verticalAdjustment,
    'vertical_adjustment_unit': r.verticalAdjustmentUnit,
    'horizontal_adjustment': r.horizontalAdjustment,
    'horizontal_adjustment_unit': r.horizontalAdjustmentUnit,
    'target_image': r.targetImage,
  };
}
