import 'package:json_schema/json_schema.dart';

import 'generated/profiles_schema.g.dart';
import 'profiles_json.dart';
import 'proto/profiles.pb.dart' as proto;

class ProfilesFieldError {
  final String field;
  final String message;
  const ProfilesFieldError(this.field, this.message);

  @override
  String toString() => '$field: $message';
}

class ProfilesValidationException implements Exception {
  final List<ProfilesFieldError> errors;
  const ProfilesValidationException(this.errors);

  @override
  String toString() => 'ProfilesData validation failed:\n${errors.join('\n')}';
}

abstract final class ProfilesValidator {
  // Built once from the embedded schema constant (kProfilesSchemaJson,
  // generated by bin/embed_schema.dart) and reused for every validate()
  // call — JsonSchema.create() parses the whole schema, so this avoids
  // repeating that work per validation.
  static JsonSchema? _schemaCache;
  static JsonSchema get _schema =>
      _schemaCache ??= JsonSchema.create(kProfilesSchemaJson);

  static void validate(proto.ProfilesData data) {
    final json = profilesDataToJson(data);
    final results = _schema.validate(json);
    if (results.errors.isEmpty) return;

    final errors = [
      for (final e in results.errors)
        ProfilesFieldError(_fieldPath(e.instancePath), e.message),
    ];
    throw ProfilesValidationException(errors);
  }

  // json_schema reports errors as JSON Pointers (e.g. "/profiles/0/weapon");
  // strip the leading slash so field paths read like a normal accessor path.
  static String _fieldPath(String instancePath) {
    var path = instancePath;
    if (path.startsWith('/')) path = path.substring(1);
    return path.isEmpty ? 'profiles' : path;
  }
}
