import 'package:json_schema/json_schema.dart';

import 'generated/settings_schema.g.dart';
import 'proto/settings.pb.dart' as proto;
import 'settings_json.dart';

class SettingsFieldError {
  final String field;
  final String message;
  const SettingsFieldError(this.field, this.message);

  @override
  String toString() => '$field: $message';
}

class SettingsValidationException implements Exception {
  final List<SettingsFieldError> errors;
  const SettingsValidationException(this.errors);

  @override
  String toString() => 'SettingsData validation failed:\n${errors.join('\n')}';
}

abstract final class SettingsValidator {
  // Built once from the embedded schema constant (kSettingsSchemaJson,
  // generated by bin/embed_schema.dart) and reused for every validate()
  // call — JsonSchema.create() parses the whole schema, so this avoids
  // repeating that work per validation.
  static JsonSchema? _schemaCache;
  static JsonSchema get _schema =>
      _schemaCache ??= JsonSchema.create(kSettingsSchemaJson);

  static void validate(proto.SettingsData data) {
    final json = settingsDataToJson(data);
    final results = _schema.validate(json);
    if (results.errors.isEmpty) return;

    final errors = [
      for (final e in results.errors)
        SettingsFieldError(_fieldPath(e.instancePath), e.message),
    ];
    throw SettingsValidationException(errors);
  }

  // json_schema reports errors as JSON Pointers (e.g. "/unit_settings/angular");
  // strip the leading slash so field paths read like a normal accessor path.
  static String _fieldPath(String instancePath) {
    var path = instancePath;
    if (path.startsWith('/')) path = path.substring(1);
    return path.isEmpty ? 'settings' : path;
  }
}
